steps:
  # 1. Build the container image using the modern Artifact Registry path
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-repo/mcp-server:$COMMIT_SHA', 
      '.'
    ]

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-repo/mcp-server:$COMMIT_SHA'
    ]

  # 3. Run Unit Tests (Inside the newly built container)
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-repo/mcp-server:$COMMIT_SHA'
    id: 'Test'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/']

  # 4. Inject the new image tag into service.yaml
  # Note: Using '|' as a delimiter in sed to handle the '/' in the Registry URL
  - name: 'bash'
    id: 'Inject Image'
    args:
      - '-c'
      - |
        sed -i "s|image: .*|image: us-central1-docker.pkg.dev/$PROJECT_ID/mcp-repo/mcp-server:$COMMIT_SHA|g" service.yaml

  # 5. Deploy to Cloud Run using the manifest file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'service.yaml'
      - '--region=us-central1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-repo/mcp-server:$COMMIT_SHA'