steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA', '.']

  # 2. Push the image to GCR (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smartgrid-mcp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      # Environmental configurations for managed services
      - '--set-env-vars'
      - 'MCP_TRANSPORT=sse,INFLUX_ORG=myorg,INFLUX_BUCKET=energy'
      - '--update-env-vars'
      - 'INFLUX_URL=https://YOUR_MANAGED_INFLUX_DOMAIN'

images:
  - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
